name: checkin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  file_picker: ^10.1.9
  device_info_plus: ^11.4.0
  file_saver: ^0.2.14
  mime: ^2.0.0
  flutter_file_dialog: ^3.0.2
  path: ^1.9.1
  flutter_local_notifications: ^19.3.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

  flutter_launcher_icons: ^0.14.3  # Pastikan untuk menggunakan versi terbaru

flutter_icons:
  android: true
  ios: false
  image_path: "asset/icon/logo_checkin.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "asset/icon/logo_checkin.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  
  uses-material-design: true
  assets:
  # - asset/app/.env
    - asset/background/
    - asset/fonts/
    - asset/icon/
    - asset/images/
    - asset/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-Black.ttf
        - asset: asset/fonts/Montserrat-BlackItalic.ttf
        - asset: asset/fonts/Montserrat-Bold.ttf
        - asset: asset/fonts/Montserrat-BoldItalic.ttf
        - asset: asset/fonts/Montserrat-ExtraBold.ttf
        - asset: asset/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: asset/fonts/Montserrat-ExtraLight.ttf
        - asset: asset/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: asset/fonts/Montserrat-Italic.ttf
        - asset: asset/fonts/Montserrat-Light.ttf
        - asset: asset/fonts/Montserrat-LightItalic.ttf
        - asset: asset/fonts/Montserrat-Medium.ttf
        - asset: asset/fonts/Montserrat-MediumItalic.ttf
        - asset: asset/fonts/Montserrat-Regular.ttf
        - asset: asset/fonts/Montserrat-SemiBold.ttf
        - asset: asset/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: asset/fonts/Montserrat-Thin.ttf
        - asset: asset/fonts/Montserrat-ThinItalic.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: asset/fonts/PlayfairDisplay-BlackItalic.ttf
        - asset: asset/fonts/PlayfairDisplay-Bold.ttf
        - asset: asset/fonts/PlayfairDisplay-BoldItalic.ttf
        - asset: asset/fonts/PlayfairDisplay-ExtraBold.ttf
        - asset: asset/fonts/PlayfairDisplay-ExtraBoldItalic.ttf
        - asset: asset/fonts/PlayfairDisplay-Italic.ttf
        - asset: asset/fonts/PlayfairDisplay-Medium.ttf
        - asset: asset/fonts/PlayfairDisplay-MediumItalic.ttf
        - asset: asset/fonts/PlayfairDisplay-Regular.ttf
        - asset: asset/fonts/PlayfairDisplay-SemiBold.ttf
        - asset: asset/fonts/PlayfairDisplay-SemiBoldItalic.ttf

    - family: TitilliumWeb
      fonts:
      - asset: asset\fonts\TitilliumWeb-Black.ttf
      - asset: asset\fonts\TitilliumWeb-Bold.ttf
      - asset: asset\fonts\TitilliumWeb-BoldItalic.ttf
      - asset: asset\fonts\TitilliumWeb-ExtraLight.ttf
      - asset: asset\fonts\TitilliumWeb-ExtraLightItalic.ttf
      - asset: asset\fonts\TitilliumWeb-Italic.ttf
      - asset: asset\fonts\TitilliumWeb-Light.ttf
      - asset: asset\fonts\TitilliumWeb-LightItalic.ttf
      - asset: asset\fonts\TitilliumWeb-Regular.ttf
      - asset: asset\fonts\TitilliumWeb-SemiBold.ttf
      - asset: asset\fonts\TitilliumWeb-SemiBoldItalic.ttf

    - family: LilitaOne
      fonts:
      - asset: asset\fonts\LilitaOne-Regular.ttf